server:
  host: "0.0.0.0"
  port: 32960

log:
  level: "debug"
  filename: "logs/server.log"
  max_size: 10
  max_backups: 5
  max_age: 30
  compress: false

auth:
  users:
    - username: "admin"
      password: "123456"

rabbitmq:
  url: "amqp://admin:xxx@xxxx:5672"
  virtual_host: /dev
  exchange: "e_car_event"
  routing_key: "k_car.event"
  queue_name: "q_carEvent"